
@startuml activity-projets
title Workflow pour le module Projets 
scale 200 width
scale 2000 height

|Gestionnaires des RH/Ventes|
    :Renseigner les **Clients**;

|#AntiqueWhite|Gestionnaire des projets|
start

partition Configuration {
    :Renseigner les **Types d'activtés**;
    :Renseigner les **Etiquettes des taches**;
    :Activer l'option **Sous-tâches**;
    :Activer l'option **Feuilles de temps sur les tâches**;
    :Créer un nouveau modèle de **Temps de travail** adapté;
    :Paramtérer l'**Unité d'encodage** à utiliser;
}

|Gestionnaires des RH/Ventes|
    :Renseigner les **Employés** membres des équipes \nprojets et le **Coût de leurs feuille de temps**;

|Chef de projet|
:Créer un Projet;
:Ajouter des pièces jointes;
:Configuer les étapes (colonnes);

repeat
    :Ajouter des taches et renseigner \nle champ **Heures planifiées**;
    :Créer des sous-tâches et les \nrelier à leurs taches parentes;
    :Affecter les sous-taches \nà des memebres de l'équipe;
repeat while (Taches restantes) is (Oui)

fork

repeat
    :Renseigner les volumes horaires \nréalisées dans chaque sous-tâche;
    :Faire avancer les taches dans le pipeline;
    :Mettre à jour l'état des taches (code couleurs);
repeat while (Taches finalisées) is (Non)

fork again 
|#AntiqueWhite|Membre équipe projet|
    :Visuliser les volumes horaires réalisés \ndans le module **Feuilles de temps**;
    :Visualiser la liste de toutes \nles feuilles de temps;

|Chef de projet|
end fork

|#AntiqueWhite|Gestionnaire des projets|
:Analyses par employé / par tache / par projet;

end

@enduml